[versions]
androidx-activity = "1.11.0"

kotlin = "2.2.20"

[plugins]
android-application = "com.android.application:8.13.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-core = "androidx.core:core-ktx:1.17.0"

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
compose-runtime = "androidx.compose.runtime:runtime:1.9.1"
compose-material3 = "androidx.compose.material3:material3:1.5.0-alpha04"
